feat : Add Spotify scraper service
wafflestudio/feelin-core-server pull request #19
Opened 2023-01-01 11:16 UTC by jm020827

- Add Spotify playlist / track / user scraper service (User scraper and authdata are not completed yet)

2023-01-05 17:16 UTC, jm020827 commented
fix : Fix playlistService error 에서 발생한 error가 저번 회의 때 말씀해주신 대로 바꾼 구조 때문이더라구요. 그래서 구조는 알맞게 맞춰뒀는데 parameter로 들어가는 cookieString에 뭐가 들어가야할지 잘 모르겠어서 대충 채워뒀습니다. 문제가 생기면 아예 구조를 다시 원래대로 돌려놓고 새로운 방법을 찾아봐도 좋습니다.

2023-01-05 17:18 UTC, jm020827 commented
chore : package.json and yarn.lock updated 에서는 위 문서들이 yarn install 한번 하면서 업데이트 된 것 같은데 확인해보시구 혹시라도 충돌 생길 것 같으면 commit 취소하겠습니다. (그리고 이 커밋이 chore 타입인지는 정확히 모르겠지만.. 일단 이렇게 달아놨습니다)

2023-01-06 15:31 UTC, james0248 requested changes
일부 코드가 flo거에서 변화가 없는것 같습니다. 재민님이 말씀해주신 안돌아가는 이슈는 제가 해결해놨고 수정사항 반영해주시면 제가 적당히 손보겠습니다.

2023-01-06 15:31 UTC, james0248 commented on src/track-scraper/spotify-track-scraper.service.ts
>          // TODO: Implement me
p2; 마찬가지로 주석 지워주세요

2023-01-06 15:31 UTC, james0248 commented on src/track-scraper/spotify-track-scraper.service.ts
> +        });
p2; 이것도 뭔가 이상한 것 같은데 Spotify 문서보고 작성한 코드 맞을까요? 돌아오는 API 형식 보고 그거에 맞춰서 코드 작성해주세요

2023-01-06 15:31 UTC, james0248 commented on package.json
> +        "nestjs": "^0.0.1",
p2; 이건 뭔가요?

2023-01-06 15:31 UTC, james0248 commented on src/playlist-scraper/spotify-playlist-scraper.service.ts
>  export class SpotifyPlaylistScraper implements PlaylistScraper {
p3; 안쓰는 주석 지워주세요

2023-01-06 19:35 UTC, jm020827 commented on package.json
> +        "nestjs": "^0.0.1",
@nestjs/common 을 yarn add 했어야했는데 실수로 nestjs만 yarn add했던게 남아있는 것 같습니다. 확인해주셔서 감사합니다. 불필요한 패키지이니 지워두겠습니다.

2023-01-06 20:16 UTC, jm020827 commented on src/playlist-scraper/spotify-playlist-scraper.service.ts
> +                //coverUrl -> flo playlist response json 구조를 알아야 할 것 같음. 우선은 가장 큰 사이즈의 앨범커버 url으로
flo api response 상의 coverUrl이 어떻게 되어있는지 몰라서 우선은 가장 큰 사이즈의 앨범 커버 이미지 url로 coverUrl에 넣어뒀습니다!

2023-01-07 08:06 UTC, james0248 commented on src/track-scraper/spotify-track-scraper.service.ts
> +                album: track.album.name,
p2; 아직 형식이 안맞는 것 같아요. `artists`는 `IArtist

2023-01-07 08:11 UTC, james0248 reviewed
거의다 마무리된것 같아요. `TrackScraper` 부분만 마지막으로 확인해주세요

2023-01-07 08:11 UTC, james0248 commented on src/track-scraper/spotify-track-scraper.service.ts
> +        });
p2; 아직 형식이 안맞는 것 같아요. artists는 `IArtist` 타입인데 지금 보이는 걸로는 이름만 가져온 것 같네요. 컴파일 된 이유는 any 타입이여서 입니다. `ITrack` 타입을 잘 확인하고 변환해주세요. 아래도 마찬가지입니다.

2023-01-07 08:11 UTC, james0248 commented on src/playlist-scraper/spotify-playlist-scraper.service.ts
> +        const addResponse = await axios.post(addTracksToPlaylistUrl, null, {
p4; 결과로 뭐 안할거면 await만 해도 충분할것 같아요

2023-01-08 07:22 UTC, james0248 approved these changes

2023-01-08 07:23 UTC, merged